modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="https://github.com/TheOnlyTails/RubyMod/issues"

[[mods]]

modId="ruby"

version="1.16.1-0.5.0"

displayName="Ruby Mod"

updateJSONURL="http://myurl.me/"

displayURL="https://github.com/TheOnlyTails/RubyMod"

logoFile="logo.png"

credits="Thanks for this example mod goes to Forge and TechnoVision"

authors="TheOnlyTails"

description='''
This mod adds rubies. They don't do anything yet, but at least they're there!
'''

[[dependencies.examplemod]]

    modId="forge"

    mandatory=true

    versionRange="[31,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"
