modLoader="javafml"

loaderVersion="[31,)"

issueTrackerURL="https://github.com/TheOnlyTails/RubyMod/issues"

[[mods]]

modId="ruby"

version="1.16.1-0.7.1"

displayName="Ruby Mod"

updateJSONURL="http://myurl.me/"

displayURL="https://github.com/TheOnlyTails/RubyMod"

logoFile="logo.png"

credits="""
Thanks for this mod goes to Forge, for providing the modding framework,
 TechnoVision, for creating the tutorial series that helped me create it,
 BlockBench, for giving me the tools to create the custom block models,
 and much more people.

 Credit to Jelly Dash for creating the beautiful textures for the Ruby sheep and the ruby wool.
"""

authors="TheOnlyTails"

description='''
This mod adds rubies. They don't do anything yet, but at least they're there!
'''

[[dependencies.examplemod]]

    modId="forge"

    mandatory=true

    versionRange="[32,)"

    ordering="NONE"

    side="BOTH"

[[dependencies.examplemod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1]"
    ordering="NONE"
    side="BOTH"
